### ISSUE TITLE
The performance result

### ISSUE THREAD

**Issue by YasuoFly** [yqlvcoding/GLAattack#1]
Thank you very much to provide your awsome method, but my reproduced result looks something wrong. Could you help me?

There is my reproduced parameter with the task "ImagenetCLS":
`   parser.add_argument('--generate_model_name', type=str, default='ViT-B/16')

    parser.add_argument('--seed', type=int, default=1024)
    parser.add_argument('--device', type=str, default='cpu')
    parser.add_argument('--gpu', type=str, default='0', help='gpu device.')
    parser.add_argument('--cpu_num', type=int, default=4)
    parser.add_argument('--batch_size', type=int, default=18)
    parser.add_argument('--mean', type=float, default=None)
    parser.add_argument('--std', type=float, default=None)
    parser.add_argument('--epsilon', type=float, default=16/255)
    parser.add_argument('--steps', type=int, default=60)
    parser.add_argument('--init_adam_lr', type=int, default=0.005, help='do not change here, change in cmd parameters')
    parser.add_argument('--multi_step_size', type=float, default=None)
    parser.add_argument('--mid_layer', type=int, default=4, help='middle layer activations for calculate loss')
    parser.add_argument('--use_adam', type=int, default=1, help="0 means sgd, others(like 1) means using adam")
    parser.add_argument('--file_p', type=str, default=None)
    parser.add_argument('--name_last', type=str, default="rebuttal_steps60")
    parser.add_argument('--l2reg', type=str, default=0)
    parser.add_argument('--l2reg_alpha', type=float, default=0.1, help='not change here, change in cmd parameters')
    parser.add_argument('--no_save', type=int, default=0)
    parser.add_argument('--patch_size', type=int, default=16)
    parser.add_argument('--range_left', type=float, default=0.85)
    parser.add_argument('--overwrite', type=int, default=0, help='regenerate adversarial examples')`
and the result

![image](https://github.com/yqlvcoding/GLAattack/assets/76839625/67a25528-ff92-48ac-a3b7-1cd00245c9b6)

**Comment by yqlvcoding** [comment]
Thanks for your try. The run script is somewhat different from the default parameters, but I'm so busy with other things these days, I will try my best to finish Readme and upload all the run scripts this weekend  (or, next weekend as there are too many other things to solve

**Comment by YasuoFly** [comment]
@yqlvcoding Wow!! Thank you for you quickly reply. If you have some free time I hope you can take a look at my parameters to see if they are incorrect, I don't know which parameters are wrong. I look forward to your readme file, thank you very much!
